apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"spot-oceancd-controller"},"name":"spot-oceancd-controller","namespace":"oceancd"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"spot-oceancd-controller"}},"template":{"metadata":{"labels":{"app":"spot-oceancd-controller"}},"spec":{"containers":[{"env":[{"name":"TOKEN","valueFrom":{"secretKeyRef":{"key":"token","name":"spot-oceancd-controller-token"}}},{"name":"SAAS_URL","valueFrom":{"secretKeyRef":{"key":"saasUrl","name":"spot-oceancd-controller-token"}}},{"name":"NODE_NAME","valueFrom":{"fieldRef":{"fieldPath":"spec.nodeName"}}},{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}}],"image":"spotinst/spot-oceancd-controller:0.0.1","imagePullPolicy":"Always","name":"spot-oceancd-controller","ports":[{"containerPort":8000}],"resources":{"limits":{"cpu":"500m","memory":"128Mi"}},"volumeMounts":[{"mountPath":"/tls","name":"spot-oceancd-controller-tls","readOnly":true}]}],"imagePullSecrets":[{"name":"aws-ecr-credentials"}],"volumes":[{"name":"spot-oceancd-controller-tls","secret":{"secretName":"spot-oceancd-controller-tls"}}]}}}}
  creationTimestamp: "2021-11-15T08:40:19Z"
  generation: 1
  labels:
    app: spot-oceancd-controller
  name: spot-oceancd-controller
  namespace: oceancd
  resourceVersion: "36979"
  uid: 61714295-a385-4b0c-a5a4-70ec5778cddf
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spot-oceancd-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spot-oceancd-controller
    spec:
      containers:
      - env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: spot-oceancd-controller-token
        - name: SAAS_URL
          valueFrom:
            secretKeyRef:
              key: saasUrl
              name: spot-oceancd-controller-token
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: spotinst/spot-oceancd-controller:0.0.1
        imagePullPolicy: Always
        name: spot-oceancd-controller
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tls
          name: spot-oceancd-controller-tls
          readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: aws-ecr-credentials
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: spot-oceancd-controller-tls
        secret:
          defaultMode: 420
          secretName: spot-oceancd-controller-tls
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-11-15T08:40:19Z"
    lastUpdateTime: "2021-11-15T08:40:28Z"
    message: ReplicaSet "spot-oceancd-controller-777f8b9578" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-11-17T08:03:31Z"
    lastUpdateTime: "2021-11-17T08:03:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
